from os import path, mkdir
import globais
from criador_json import criador_json as cj

default_texts = {
    "driver_found": "found SentinelaDriver, registering monitor...",
    "tag_driver": "DRIVER",
    "tag_error": "ERROR",
    "tag_ok": "OK",
    "tag_clean": "CLEAN",
    "tab_blocked": "BLOCKED",
    "tag_system": "SYSTEM",
    "error": "Error",
    "scanning": "Verified",
    "driver_not_found": "SentinelaDriver not available, trying again in 30 secs.",
    "debug_startup_file_check": "Checking some files...",
    "startup_file_check": "Startup checking...",
    "virus_found": "Virus found",
    "output": "Output",
    "startup_check_finished": "Startup verification completed successfully.",
    "debug_check_ends": "End of startup checking...",
    "sched_update": "Starting scheduled update...",
    "update_next_time": "Updating the next update timer...",
    "starting_timer": "Starting ciclic timer...",
    "starting_singleshot_timer": "Starting singleshot timer.",
    "next_update": "next update:",
    "time_next_update": "Time of the next update",
    "debug_driver_closing": "Closing driver...",
    "debug_stop_workers": "Stoping workers...",
    "config_save": "Saving configuration...",
    "debug_stop_tray": "Tray thread has ended.",
    "waiting_stop_tray": "Waiting for the tray thread to finish...",
    "start_shutdown": "Starting shutdown sequence...",
    "sentinela_background": "Sentinela continues to run in the background.",
    "sentinela_active": "Active Protection",
    "block_virus_success": "Virus has been blocked",
    "update_not_successful": "The update process did not complete successfully.",
    "update_successful": "Update completed successfully.",
    "start_up": "Starting up...",
    "disabled_60min": "Disabled for 60 minutes...",
    "database_update": "Database update (Freshclam)",
    "clamav_path": "ClamAV path",
    "select_clamav_folder": "Select the ClamAV installation folder.",
    "about_msg": "About Sentinela Zero-Trust",
    "released_in": "released in",
    "by": "by",
    "visit_github": "project github",
    "label_update": "Updating label with current version",
    "log_enable": "Enable logging",
    "official_bypass": "Do not verify officially signed files",
    "clamd_conecting": "Trying to connect",
    "about": "About",
    "change_clamav_folder": "Change ClamAV folder",
    "quit_menu": "Shutdown (stop protection)",
    "open_dashboard": "Open Dashboard",
    "shared_mem_startup": "Initializing internal shared memory with:",
    "default_title": "Warning",
    "another_instance_running": "Another instance is already running.",
    "popup_msg": "The app is already running!\nVersion found:",
    "popup_title": "Unable to start",
    "translated_by": "Translated by",
    "translator_email": "joaogojunior@gmail.com",
    "translator": "João Guilherme",
    "driver_thread_ends": "Driver Thread: Successfully stopped.",
    "sentinela_starting": "Sentinela is active, number of workers",
    "reg_monitor_msg": "Monitor successfully registered.",
    "compromised_msg": "Your system is compromised; it's best to use an offline solution.",
    "compromised_text": "Critical system files have been compromised.\nUse an offline option or consider reformatting.",
    "compromised_title": "Compromised system",
    "service_online": "Clamd service is online",
    "service_not_running": "Service not running, check again in 30s.",
    "init_service_not_running": "init: clamd is not available... checking again in 30s.",
    "checking_service": "Checking if clamd service is running...",
    "init_checking_service": "init: checking if clamd is running...",
    "my": "My",
    "hheader_label_datetime": "Date / Hour",
    "hheader_label_status": "Status",
    "hheader_label_pid": "PID",
    "hheader_label_file": "File",
    "hheader_label_details": "Details",
    "already_updated": "The time for the next update has already been updated.",
    "connection_deny_with_retry": "Connection refused (timeout 30s).",
    "not_connected_with_retry": "Not connected, waiting 30 seconds to try again.",
    "reload_finished": "Reload complete and service ready!",
    "waiting_db_load": "Awaiting loading the database.",
    "not_found": "not found",
    "error_target_is_empty": "Error: target cannot be empty.",
    "error_file_not_found": "Error: File not found.",
    "checking_health": "Checking health of",
    "certificate": "Certificate",
    "clamav_file_clean": "Clavam says the binary is clean!",
    "virus": "virus",
    "capitalized_virus": "Virus",
    "error_checking_file": "Error while trying to verify the file.",
    "blocking_process": "Blocking the process",
    "block_msg": "because it's very strange that ClamAV cant processing some file...",
    "oficial_embedded_cert": "Official file (embedded certificate)",
    "error_admin": "ERROR: Admin Context",
    "error_file": "ERROR: File access",
    "not_signed": "Unsigned file",
    "oficial_cat_cert": "OFFICIAL Archive (catalog)",
    "not_trusted": "UNTRUSTED FILE",
    "started": "started",
    "received_exit": "received exit signal.",
    "ended": "ended.",
    "driver_restarted": "Driver has been reset.",
    "error_unreg": "Error unregistering",
    "driver_unloaded": "Driver is shutdown, waiting for driver loop to abort...",
    "verdict_timetout": "Verdict ignored: The driver has already discarted context due to timeout.",
    "context_invalid": "Error: The context for the process is no longer valid due to timeout.",
    "critical_ioctl_error": "Critical error in IOCTL call",
    "data_too_small": "Error: data was empty or too small...",
    "new_buffer_size": "New buffer size",
    "invalid_driver_handle": "Error: The driver handle has been temporarly invalidated, please wait a moment...",
    "ioctl_error": "Error in IOCTL call",
    "new_job": "Received a new job",
    "clamd_online": "Clamd service  is online.",
    "clamd_conneted": "Successfully connected to clamd.",
    "clamd_conect_error": "Error testing clamd connectivity.",
    "clamd_ping_failed": "Clamd did not responded to ping...",
    "reconecting": "reconnecting...",
    "clamd_not_found": "Clamd service not found...",
    "accept_and_continue": "Accepting to continue...",
    "bug_empty_filename": "Bug: the path came up empty, this shouldn't happen.",
    "empty_path": "Empty path",
    "send_verdict": "Sending verdict to the driver",
    "warning": "Warning",
    "verdict_not_sended": "did not send the verdict.",
    "job_end": "Finishing job",
    "converting_path": "Converting path",
    "init_shutdown": "Initiating shutdown...",
    "pending_threads": "Checking pending threads",
    "still_alive": "still alive",
    "stop_threads": "Threads completed.",
    "status": "Get driver status",
    "driver_not_available": "Driver is not available."
}

textos_padrao = {
    "driver_found": "SentinelaDriver encontrado, registrando monitor...",
    "tag_driver": "DRIVER",
    "tag_error": "ERRO",
    "tag_ok": "OK",
    "tag_clean": "LIMPO",
    "tab_blocked": "BLOQUEADO",
    "tag_system": "SISTEMA",
    "error": "Erro",
    "scanning": "Verificado",
    "driver_not_found": "SentinelaDriver não esta disponivel, tentando novamente em 30 seg.",
    "debug_startup_file_check": "Checando alguns arquivos ...",
    "startup_file_check": "Verificação de inicialização...",
    "virus_found": "Encontrado Virus",
    "output": "Saida",
    "startup_check_finished": "Verificação de inicialização concluída com sucesso.",
    "debug_check_ends": "Fim da checagem...",
    "sched_update": "Iniciando atualização agendada...",
    "update_next_time": "Atualizando próxima hora...",
    "starting_timer": "iniciado timer ciclico...",
    "starting_singleshot_timer": "Iniciando timer singleshot...",
    "next_update": "próxima atualizacao:",
    "time_next_update": "Horário da próxima atualização",
    "debug_driver_closing": "Fechando o driver...",
    "debug_stop_workers": "Encerrando workers...",
    "config_save": "Salvando configuração...",
    "debug_stop_tray": "Thread do ícone de notificação finalizada.",
    "waiting_stop_tray": "Aguardando finalização da thread do ícone da bandeja...",
    "start_shutdown": "Iniciando encerramento coordenado...",
    "sentinela_background": "Sentinela continua rodando em segundo plano.",
    "sentinela_active": "Proteção ativa",
    "block_virus_success": "Virus bloqueado com sucesso...",
    "update_not_successful": "O processo de atualização não concluiu com êxito.",
    "update_successful": "Atualização concluída com sucesso.",
    "start_up": "Iniciando...",
    "disabled_60min": "Desativado por 60 minutos...",
    "database_update": "Atualizar assinaturas (Freshclam)",
    "clamav_path": "Caminho ClamAV",
    "select_clamav_folder": "Selecionar pasta de instalação do ClamAV",
    "about_msg": "Sobre o Sentinela Zero-Trust",
    "released_in": "lançado em",
    "by": "por",
    "visit_github": "Visite meu github",
    "label_update": "Atualizando label com versão atual",
    "log_enable": "Habilitar log das workers",
    "official_bypass": "Liberar arquivos oficiais",
    "clamd_conecting": "Tentando se conectar",
    "about": "Sobre",
    "change_clamav_folder": "Alterar pasta ClamAV",
    "quit_menu": "Encerrar (interrompe a proteção)",
    "open_dashboard": "Abrir Dashboard",
    "shared_mem_startup": "Iniciando memória compartilhada com:",
    "default_title": "Aviso",
    "another_instance_running": "Outra instância já está em execução.",
    "popup_msg": "O aplicativo já está rodando!\nversão encontrada:",
    "popup_title": "Não foi possível iniciar",
    "translated_by": "Traduzido por",
    "translator_email": "joaogojunior@gmail.com",
    "translator": "João Guilherme",
    "driver_thread_ends": "Thread do Driver: Encerrada com sucesso.",
    "sentinela_starting": "Sentinela ativa, quantidade de workers",
    "reg_monitor_msg": "Monitor registrado com sucesso.",
    "compromised_msg": "Seu sistema esta comprometido, melhor utilizar uma solução offline.",
    "compromised_text": "Arquivos críticos do sistema foram comprometidos,\nutilize uma opção offline ou considere reformatar.",
    "compromised_title": "Sistema comprometido",
    "service_online": "Serviço online",
    "service_not_running": "Serviço clamd não esta rodando, verificando novamente em 30s.",
    "init_service_not_running": "init: clamd não esta disponivel... checando novamente em 30s.",
    "checking_service": "Checando se o serviço do clamd esta rodando...",
    "init_checking_service": "init: checando se o clamd esta rodando...",
    "my": "Meu",
    "hheader_label_datetime": "Data / Hora",
    "hheader_label_status": "Status",
    "hheader_label_pid": "PID",
    "hheader_label_file": "Arquivo",
    "hheader_label_details": "Detalhes",
    "already_updated": "Horário da próxima atualização já está atualizado.",
    "connection_deny_with_retry": "Conexão recusada (timeout 30s).",
    "not_connected_with_retry": "Não conectado, aguardando 30s para tentar novamente.",
    "reload_finished": "Reload concluído e serviço pronto.",
    "waiting_db_load": "Aguardando carregamento da base de dados",
    "not_found": "não encontrado",
    "error_target_is_empty": "Erro: alvo não pode ser vazio.",
    "error_file_not_found": "Erro: Arquivo não encontrado.",
    "checking_health": "Checando saúde de",
    "certificate": "Certificado",
    "clamav_file_clean": "clamav diz que o binário está limpo!",
    "virus": "vírus",
    "capitalized_virus": "Vírus",
    "error_checking_file": "Erro ao tentar verificar o arquivo",
    "blocking_process": "Bloqueando o processo",
    "block_msg": "por ser muito estranho que o clamav não processe algum arquivo...",
    "oficial_embedded_cert": "Arquivo OFICIAL (Certificado embutido)",
    "error_admin": "ERRO: Admin Context",
    "error_file": "ERRO: Acesso Arquivo",
    "not_signed": "Arquivo NÃO ASSINADO",
    "oficial_cat_cert": "Arquivo OFICIAL (Catálogo)",
    "not_trusted": "Arquivo NÃO CONFIÁVEL",
    "started": "iniciado",
    "received_exit": "recebeu sinal de saída.",
    "ended": "finalizado.",
    "driver_restarted": "Driver resetado para o estado inicial.",
    "error_unreg": "Erro ao desregistrar",
    "driver_unloaded": "Driver já encerrou, aguardando o loop do driver finalizar...",
    "verdict_timetout": "Veredito ignorado: O Driver já processou por Timeout.",
    "context_invalid": "Erro: O contexto para o processo não é mais válido.",
    "critical_ioctl_error": "Erro crítico no IOCTL",
    "data_too_small": "Erro: data veio vazio ou muito pequeno...",
    "new_buffer_size": "Novo tamanho do buffer",
    "invalid_driver_handle": "Erro: O handle do driver foi invalidado, esperando um pouco...",
    "ioctl_error": "Erro no IOCTL",
    "new_job": "Recebeu novo job",
    "clamd_online": "Serviço clamd online.",
    "clamd_conneted": "Conectado ao clamd com sucesso.",
    "clamd_conect_error": "Erro ao testar conectividade do clamd",
    "clamd_ping_failed": "Clamd não respondeu ao ping...",
    "reconecting": "reconectando...",
    "clamd_not_found": "Serviço clamd não encontrado...",
    "accept_and_continue": "Aceitando para continuar...",
    "bug_empty_filename": "Bug: o caminho veio vazio, isso não devia ocorrer.",
    "empty_path": "Caminho vazio",
    "send_verdict": "enviando veredito para o driver",
    "warning": "Aviso",
    "verdict_not_sended": "não enviou o veredito.",
    "job_end": "finalizando job",
    "converting_path": "Convertendo caminho",
    "init_shutdown": "Iniciando desligamento...",
    "pending_threads": "Verificando threads pendentes",
    "still_alive": "ainda viva",
    "stop_threads": "Threads finalizadas.",
    "status": "Obter status do driver",
    "driver_not_available": "Driver não está disponível."
}

# carrega textos utilizados na interface do arquivo ou do padrão
# lang_path = path.join(globais.caminho_home, "lang")
lang_path = "lang"

if not path.isdir(lang_path):
    mkdir(lang_path)

text_interface_dict = {
    "pt-BR": cj.carrega_ou_cria_config(path.join(lang_path, "pt-BR.json"), textos_padrao),
    "en-US": cj.carrega_ou_cria_config(path.join(lang_path, "en-US.json"), default_texts)
}